context:
  filter: []
  identifier_filter_list: []

pipeline:
  input:
    http:
      type: rest_api
      account: '%akeneo_read_connection%'
      endpoint: '%endpoint%'
      method: GET
      filter: '%filter%'
      identifier_filter_list: '%identifier_filter_list%'
  output:
    writer:
      type: jsonl
      filename: 'read/akeneo_%endpoint%.jsonl'
      skip_if_exists: true